### ISSUE TITLE
Add Matt's docassemble administration video

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/legal-tech-class#15]

**Comment by nonprofittechy** [comment]
@mnewsted it would be great to get a page here with your notes from your class, and your video. It could be added to this page: https://suffolklitlab.org/legal-tech-class/docs/practical-guide-docassemble/maintaining-docassemble#updating-the-assemblyline-packages

I'd be happy to meet with you to go over editing it. It's markdown, so not too different from a standard Docassemble interview.

**Comment by mnewsted** [comment]
Thanks for taking the initiative, @nonprofittechy ! I was going to ask you about this.

Yes, I think that could be a good place. Some of what I covered overlaps with what you already have here and elsewhere. I'd like to pare down my content (to just what is new) and then try to fit it in. Once I figured that out, could we meet to discuss editing? I'm happy to share drafts as I go, too.
